### ISSUE TITLE
Add specs to categories and tally up coverage per category

### ISSUE THREAD

**Issue by edd** [vegaprotocol/approbation#32]
https://github.com/vegaprotocol/specs/tree/main/protocol#readme defines rough categories for each spec. Currently `approbation check-references` gives us an idea of coverage per spec, and coverage overall. This ticket is to assign each spec to a category, and to grab coverage for that.

We *think* this will be a useful metric. It probably is. This task is to *produce* the metric, and if it turns out to be useful.

# Tasks
- [ ] Using an ugly JSON block passed in via command parameter, assign every spec to a category
- [ ] Update `check-references` to use categories to tally up ACs per category
- [ ] Add that to the output

Assuming this produces numbers that we find useful, this will be mibrated to some sort of config file, or label per specification
