### ISSUE TITLE
Stop publishing to NPM

### ISSUE THREAD

**Issue by edd** [vegaprotocol/approbation#79]
See: https://github.com/vegaprotocol/jenkins-shared-library/pull/413

There's no real use of this package for anyone else, so we're switching our CI to run via NPX from github. So let's stop publishing when this is merged.

# Tasks
- [x] Disable `npm` publish github action
- [x] Unpublish from `npm`
- [x] Ensure README directs people to use `npx gitub:vegaprotocol/approbation`
